name: Build

on:
  push:
    branches: [main, multiplayer]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install NASM
      uses: ilammy/msvc-dev-cmd@v1

    - name: Configure CMake
      run: cmake -B build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=RelWithDebInfo

    - name: Build
      run: cmake --build build --config RelWithDebInfo

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dusklight-multiplayer
        path: build/RelWithDebInfo/dusklight.exe
